### PR TITLE
V22F-461 cover recorder code

### PR DESCRIPTION
**Pull request by Sindarin27**
- Create tests to cover recorder code
- Use a template for the recorder output filename
- Open recorder file with trunc, as opening with app was redundant and did not clear the file if the same file was written to twice
- Move recorder constructor code to find the AppData folder to a separate function in RppUtils

### CODE REVIEW

**Review by sjoeman1 — COMMENTED** [review]
Don't think it is totally necesarry but maybe a test that tries to write less or more inputs than stated in the contructor, for the rest, very well done

**Review by sjoeman1 — COMMENTED** [review]
also dont the test need comments?

**Comment by Sindarin27** [comment]
> Don't think it is totally necesarry but maybe a test that tries to write less or more inputs than stated in the contructor, for the rest, very well done

Due to the way C++ works, giving more or less inputs will either just not read/write all variables, or read/write outside bounds. Not really something we can test for I think...

**Comment by Sindarin27** [comment]
> also dont the test need comments?

Whoops you're right, adding them in the next commit

**Comment by suppergerrie2** [comment]
> > Don't think it is totally necesarry but maybe a test that tries to write less or more inputs than stated in the contructor, for the rest, very well done
> 
> Due to the way C++ works, giving more or less inputs will either just not read/write all variables, or read/write outside bounds. Not really something we can test for I think...

If the recorder can check for this it should throw an error when it happens, and you can test for that

**Review by sjoeman1 — APPROVED** [review]

**Comment by Sindarin27** [comment]
> > Due to the way C++ works, giving more or less inputs will either just not read/write all variables, or read/write outside bounds. Not really something we can test for I think...
> 
> If the recorder can check for this it should throw an error when it happens, and you can test for that

While it is theoretically possible to check for this, it would require counting the numbers of bytes inside the array and dividing this by the size of a float. This is a bit hacky and something we agreed on not doing I believe, so...

**Review by KungFuDonkey — APPROVED** [review]

**Review by noutheesink — CHANGES_REQUESTED** [review]

**Review by noutheesink — APPROVED** [review]

**Pull request merged**
